name: Algosketch's Firebase Distribution
description: 내가 만든 액션 ㅎㅎㅎㅎㅎ

inputs:
  debug-keystore-b64:
    description: base64 encoded debug keystore
    required: true
  firebase-service-account:
    description: firebase credential json
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11

    - name: Decode keystore
      shell: bash
      run: |
        echo "${{ inputs.debug-keystore-b64 }}" | base64 --decode > debug.keystore

    - name: Write service account JSON
      shell: bash
      run: |
        echo '${{ inputs.firebase-service-account }}' > app/firebase-account.json

    - name: Restore keystore.properties
      shell: bash
      run: |
        echo "storeFile=debug.keystore" > keystore.properties
        echo "storePassword=android" >> keystore.properties
        echo "keyAlias=androiddebugkey" >> keystore.properties
        echo "keyPassword=android" >> keystore.properties

    - name: Make gradlew executable
      shell: bash
      run: chmod +x ./gradlew

    - name: Build and distribute
      shell: bash
      run: ./gradlew assembleDebug appDistributionUploadDebug