name: Firebase App Distribution
on: push
jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/firebase-distribution
        with:
          x: 13
          y: 3