name: Test CI

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Create keystore.properties
        run: |
          echo "${{ secrets.KEYSTORE_PROPERTIES }}" > keystore.properties
          echo "base.url=${{ secrets.BASE_URL }}" > local.properties
          echo "${{ secrets.GOOGLE_SERVICES }}" | base64 -d > app/google-services.json

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests (Android)
        run: ./gradlew testDebugUnitTest
